//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DX.Data.Xpo.Identity.Persistent
{

	[Persistent(@"DXUserTokens")]
	public partial class XpoDxUserToken : XpoDxBase
	{
		XpoDxUser _User;
		[Indexed(@"LoginProvider;Name", Name = @"IdxUserToken")]
		[Association(@"XpoDxUserTokenReferencesXpoDxUser")]
		public XpoDxUser User
		{
			get { return _User; }
			set { SetPropertyValue<XpoDxUser>("User", ref _User, value); }
		}
		string _LoginProvider;
		[Size(250)]
		public string LoginProvider
		{
			get { return _LoginProvider; }
			set { SetPropertyValue<string>("LoginProvider", ref _LoginProvider, value); }
		}
		string _Name;
		[Size(250)]
		public string Name
		{
			get { return _Name; }
			set { SetPropertyValue<string>("Name", ref _Name, value); }
		}
		string _Value;
		[Size(250)]
		public string Value
		{
			get { return _Value; }
			set { SetPropertyValue<string>("Value", ref _Value, value); }
		}
	}

}
