//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DX.Data.Xpo.Identity.Persistent
{

	[Persistent(@"DXRoleClaims")]
	[MapInheritance(MapInheritanceType.ParentTable)]
	public partial class XpoDxRoleClaim : XpoDxBaseClaim
	{
		XpoDxRole _Role;
		[Association(@"XpoDxRoleClaimReferencesXpoDxRole")]
		public XpoDxRole Role
		{
			get { return _Role; }
			set { SetPropertyValue<XpoDxRole>("Role", ref _Role, value); }
		}
		[PersistentAlias("[Role!Key]")]
		public string RoleId
		{
			get { return (string)(EvaluateAlias("RoleId")); }
		}
	}

}
