//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DX.Data.Xpo.IndentityServer.XPModels
{

	[Persistent(@"DXDeviceCodes")]
	public partial class XpoDeviceCode : XPLiteObject
	{
		string _UserCode;
		[Key]
		[Size(200)]
		public string UserCode
		{
			get { return _UserCode; }
			set { SetPropertyValue<string>(nameof(UserCode), ref _UserCode, value); }
		}
		string _DeviceCode;
		[Indexed(Name = @"IDXDeviceCode_DeviceCode", Unique = true)]
		[Size(200)]
		public string DeviceCode
		{
			get { return _DeviceCode; }
			set { SetPropertyValue<string>(nameof(DeviceCode), ref _DeviceCode, value); }
		}
		string _SubjectId;
		[Size(200)]
		public string SubjectId
		{
			get { return _SubjectId; }
			set { SetPropertyValue<string>(nameof(SubjectId), ref _SubjectId, value); }
		}
		string _ClientId;
		[Size(200)]
		public string ClientId
		{
			get { return _ClientId; }
			set { SetPropertyValue<string>(nameof(ClientId), ref _ClientId, value); }
		}
		DateTime _CreationTime;
		public DateTime CreationTime
		{
			get { return _CreationTime; }
			set { SetPropertyValue<DateTime>(nameof(CreationTime), ref _CreationTime, value); }
		}
		DateTime? _Expiration;
		[Indexed(Name = @"IDXDeviceCode_Expiration")]
		public DateTime? Expiration
		{
			get { return _Expiration; }
			set { SetPropertyValue<DateTime?>(nameof(Expiration), ref _Expiration, value); }
		}
		string _Data;
		[Size(SizeAttribute.Unlimited)]
		public string Data
		{
			get { return _Data; }
			set { SetPropertyValue<string>(nameof(Data), ref _Data, value); }
		}
	}

}
